### ISSUE TITLE
ERROR add kategori dan post

### ISSUE THREAD

**Issue by zanuwarakhid** [PopojiCMS/PopojiCMS#10]
Kok makin banyak yg error gan

**Comment by DwiraSurvivor** [comment]
Karena tidak ada tanggapan lagi, maka issue ini kami close.

**Comment by zanuwarakhid** [comment]
Maaf baru merespon, saya pakai bahasa indonesia dan tidak bisa di upload
file.
Baik, silahkan di close pak. ini saya masih untak atik lagi

2018-04-27 8:13 GMT+07:00 Dwira Survivor <notifications@github.com>:

**Comment by zanuwarakhid** [comment]
terima kasih atas balasannya


Pada 27 April 2018 10.08, Zanuwar Akhid <zanuwara@gmail.com> menulis:

**Comment by zanuwarakhid** [comment]
body {
width: 100% !important;
}
.ReadMsgBody {
width: 100%;
}
.ExternalClass {
width: 100%;
}
body {
-webkit-text-size-adjust: none;
}
body {
margin: 0; padding: 0;
}
img {
border: 0 none; height: auto; line-height: 100%; outline: none; text-decoration: none;
}
body {
background-color: #f8f8f8;
}



















































Halo reply@reply.github.com, Zanuwar akhid Memberikanmu Credits Sebesar Rp0!










Zanuwar akhid

mengundangmu untuk bergabung ke Bukalapak. Dapatkan Credits Rp0 milikmu dengan bergabung dan berbelanja di Bukalapak sekarang. Caranya mudah:



Bergabung & Dapatkan Credits





Klik tombol "Bergabung & Dapatkan Credits" di atas dan daftarkan akunmu


Atau kamu bisa mendaftar dengan membuka website
Bukalapak,
kemudian klik tombol "Daftar" di bagian kanan atas halaman beranda Bukalapak


Pada saat mendaftar tersebut, masukkan kode

zanuwar_akhid1oqx

pada kolom "Kode Referral"


Setelah itu kamu tinggal lakukan transaksi minimum Rp200.000 paling lambat 0 hari setelah mendaftar


Selamat! Kamu mendapatkan Credits Rp0




Yuk, daftar dan berbelanja sekarang!



bukalapak.com/rf/zanuwar_akhid1oqx































Segala bentuk informasi seperti

nomor kontak, alamat e-mail, atau password kamu bersifat rahasia.

Jangan menginformasikan data-data tersebut kepada siapa pun, termasuk kepada pihak yang mengatasnamakan Bukalapak.



























Copyright © 2019 PT Bukalapak.com. All Rights Reserved


Plaza City View Lt. 1 Jl. Kemang Timur No. 22


Jakarta Selatan Indonesia 12510















































































Anda memperoleh e-mail ini karena keanggotaan Anda pada Bukalapak.com. Anda bisa mengubah
pengaturan notifikasi
kapan pun.









Harap jangan membalas e-mail ini, karena e-mail ini dikirimkan secara otomatis oleh sistem.
