### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\sinarbajaelectric\po-includes\core\vendor\fluentpdo\BaseQuery.php on line 226

### ISSUE THREAD

**Issue by zanuwarakhid** [PopojiCMS/PopojiCMS#11]
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\sinarbajaelectric\po-includes\core\vendor\fluentpdo\BaseQuery.php on line 226

mohon pencerahannya

**Comment by tumbur** [comment]
### change  :

> private function clauseNotEmpty($clause) {
> 		if ($this->clauses[$clause]) {
> 			return (boolean) **count**($this->statements[$clause]);
> 		} else {
> 			return (boolean) $this->statements[$clause];
> 		}
> 	}


### to this : 

> private function clauseNotEmpty($clause) {
> 		if ($this->clauses[$clause]) {
> 			return (boolean) **!empty**($this->statements[$clause]);
> 		} else {
> 			return (boolean) $this->statements[$clause];
> 		}
> 	}

hopefully thats help

**Comment by zanuwarakhid** [comment]
work, thankyou
