### ISSUE TITLE
Storage XSS exists in the message desk at the front desk

### ISSUE THREAD

**Issue by MisakiKata** [PopojiCMS/PopojiCMS#20]
Front page contant
![image](https://user-images.githubusercontent.com/27627614/58938024-95db2a00-87a6-11e9-8cc3-5c46a755e1cd.png)
Write the following information in the message box.
![image](https://user-images.githubusercontent.com/27627614/58938138-c7ec8c00-87a6-11e9-817d-02589f7404bf.png)
Background administrator view message board triggers XSS
![image](https://user-images.githubusercontent.com/27627614/58938184-daff5c00-87a6-11e9-815f-92557b29c5fb.png)

**Comment by DwiraSurvivor** [comment]
Terima kasih untuk temuan ini. Kami sebagai pengembang akan segera memperbaiki masalah ini di versi berikutnya.

**Comment by DwiraSurvivor** [comment]
Sudah diperbaiki pada versi 3
