### ISSUE TITLE
Stored XSS on Post feature

### ISSUE THREAD

**Issue by avltree9798** [PopojiCMS/PopojiCMS#21]
Hi, @abdilahrf and I found a stored XSS vulnerability on the Post feature.
By intercepting the request, we are able to edit the request body to insert a XSS payload.
![](https://i.imgur.com/ifEyydR.png)
and it is executed just fine
![](https://i.imgur.com/1nnh6vC.png)

**Comment by DwiraSurvivor** [comment]
Terima kasih untuk temuan ini. Kami sebagai pengembang akan segera memperbaiki masalah ini di versi berikutnya.

**Comment by DwiraSurvivor** [comment]
Sudah diperbaiki pada versi 3

**Comment by attritionorg** [comment]
@DwiraSurvivor can you link to the fixing commit please?
