### ISSUE TITLE
Open Redirection Vulnerability

### ISSUE THREAD

**Issue by avltree9798** [PopojiCMS/PopojiCMS#22]
Hi, @abdilahrf and I found open redirection vulnerability on the PopojiCMS. The vulnerable code is on **index.php** file line number **101**
![](https://i.imgur.com/6RrMCgU.png)
notice the parameter refer was used by the code to redirect the user's to another page. So by crafting a request that using the POST method and contains the refer parameter, we could control where to redirect the user.
![](https://i.imgur.com/fI0B7H3.png)

**Comment by DwiraSurvivor** [comment]
Terima kasih untuk temuan ini. Kami sebagai pengembang akan segera memperbaiki masalah ini di versi berikutnya.

**Comment by DwiraSurvivor** [comment]
Sudah diperbaiki pada versi 3
