### ISSUE TITLE
User Level Category

### ISSUE THREAD

**Issue by zanuwarakhid** [PopojiCMS/PopojiCMS#26]
Mau tanya pak dwi, disini kan sudah ada edit untuk user levelnya berdasarkan category dll. yang mau saya tanyakan, bisa tidak user levelnya di bedakan berdasarkan post category?
Contoh : 
Category : INDONESIAKU dan MOTIVASI
User : admin1 dan admin2

user admin1 hanya bisa update / post dari Category INDONESIAKU begitupun sebaliknya. terima kasih

**Comment by DwiraSurvivor** [comment]
Bisa bisa saja...cuma harus di custom pada component categorynya.
