### ISSUE TITLE
Database Oracle

### ISSUE THREAD

**Issue by yogahilmi** [PopojiCMS/PopojiCMS#27]
Dear All, gimana cara nya yaa supaya bisa di jalankan menggunakan database Oracle?

**Comment by DwiraSurvivor** [comment]
Gunakan veri 3 : https://github.com/PopojiCMS/Popoji

**Comment by yogahilmi** [comment]
Saya coba yg versi 3 diatas, udah berhasil install. Tapi setelah itu kok minta file autoload.php yaa? Mohon pencerahannya, thankyou

**Comment by DwiraSurvivor** [comment]
Jika filenya di ambil dari github maka harus running composer di folder webnya.

composer required atau composer install

**Comment by yogahilmi** [comment]
Thanks udh bisa om.
Oiya untuk driver oracle nya gimana ya implemen nya?

**Comment by DwiraSurvivor** [comment]
Bisa pake package ini : https://github.com/yajra/laravel-oci8

**Comment by yogahilmi** [comment]
Solved.
Thanks om atas pencerahannya, sukses selalu^^
