### ISSUE TITLE
Demo.popojicms.org

### ISSUE THREAD

**Issue by aancw** [PopojiCMS/PopojiCMS#6]
Halo,

Subdomain demo.popojicms.org ada masalah atau memang sudah tidak terdaftar ya?

![popojipng](https://user-images.githubusercontent.com/6284204/30963931-93a4e1f2-a479-11e7-85ab-927e986d9a9d.png)

Thanks :)

**Comment by DwiraSurvivor** [comment]
Kami lagi migrasi server, jadi subdomain untuk sementara tidak bisa diakses.
