### ISSUE TITLE
media sosial and share

### ISSUE THREAD

**Issue by dadannurman** [PopojiCMS/PopojiCMS#9]
saya sudah coba setting di po-admin/admin.php?mod=setting#config memasukan nama, username dan id fb namun tetep tdk berfungsi, mohon pencerahan nya

**Comment by DwiraSurvivor** [comment]
Untuk sementara fitur OAuth tidak bisa digunakan karena facebook sudah mengupdate APInya. Silahkan tunggu perbaikan di versi berikutnya.
